id: I498D4047
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T10:57:55+00:00'
last_modified: '2022-06-08T05:12:21.106052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5414
  title: སྒྲུབ་ཐབས་ལ་བརྟེན་ནས་རང་གི་ནུ་བོ་བར་སྲིད་དུ་འཁྱམས་པ་དང་འཕྲད་ཚུལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1669':
      image_group_id: I3CN5416
      title: ''
      total_pages: 64
      order: 1
      base_file: 1669.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
