id: P005600
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:04.287455
source_metadata:
  id: bdr:W3CN5414
  title: སྒྲུབ་ཐབས་ལ་བརྟེན་ནས་རང་གི་ནུ་བོ་བར་སྲིད་དུ་འཁྱམས་པ་དང་འཕྲད་ཚུལ།
  author: ''
  volumes:
    17b06456387647caaf59de3beb6ee63c:
      image_group_id: I3CN5416
      title: ''
      volume_number: 1
      total_pages: 64
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
